[package]
name = "shigure"
version = { workspace = true }
license = "Apache-2.0"
authors = [ "Hasegawa Raku <raku@exhibition.jp>" ]
edition = "2021"
description = "Wasm frontend framework"

[dependencies]
futures-util = { workspace = true }
